[package]
name = "gleam"
version = "0.1.0"
authors = ["Louis Pilfold <louis@lpil.uk>"]
edition = "2018"

[dependencies]
clap = "2"
im = "12"
itertools = "0.7"

[dev-dependencies]
pretty_assertions = "0.5"
